<template>
  <div class="alert alert-info d-flex" role="alert">
        <font-awesome-icon :icon="['fas', 'info-circle']" class="me-3" />
        This section shows the log generated by the algorithm and enclosing runner software. 
    </div>
  <div>
    <span v-for="(value, key) in sections" :key="key">
      <algorithm-log-section :sectionKey="key" :sectionContent="value" />
    </span>
  </div>
</template>

<script setup>
import AlgorithmLogSection from '@/components/algorithm/run/AlgorithmLogSection.vue'
</script>

<script>
export default {
  props: {
    sections: Object
  }
}
</script>
