<template>
    <div class="alert alert-info d-flex" role="alert">
        <font-awesome-icon :icon="['fas', 'info-circle']" class="me-3" />
        This section shows the output files generated by the algorithm. These files may contain more information than the log.
    </div>

    <div v-if="!outputFiles || outputFiles.length === 0" class="alert alert-warning" role="alert">
        <font-awesome-icon :icon="['fas', 'exclamation-triangle']" class="me-3" />
        No files found. This can be due to the algorithm not having produced any valid output files (yet).
    </div>
    <table v-else class="table">
        <thead>
            <tr>
                <th>File Name</th>
                <th>Size</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="file in outputFiles" :key="file">
                <td>{{ file.filePath }}</td>
                <td>{{ prettyBytes(file.fileSize) }}</td>
                <td><a :download="file.fileName" :href="getOutputFileLink(file.filePath)" target="_blank"><font-awesome-icon :icon="['fas', 'download']" class="me-2" />Download</a></td>
            </tr>
        </tbody>
    </table>
</template>

<script setup>
import { AlgorithmRepository } from '@/repositories/AlgorithmRepository';
import prettyBytes from 'pretty-bytes'
</script>

<script>
export default {
  props: {
    runOrderId: String,
    runId: String,
    outputFiles: Array
  },
  data: () => ({
    AlgorithmRepository: new AlgorithmRepository()
  }),
  methods: {
    getOutputFileLink(filePath) {
      return this.AlgorithmRepository.getOutputFileLink(this.runOrderId, this.runId, filePath)
    }
  }
}
</script>

<style scoped>
th {
    font-weight: bold   ;
}
</style>